&nbsp;
<center>
    <font size="+2">Системи штучного інтелекту</font> 
</center>

&nbsp;
<center>
    <font size="+2">Лінійна алгебра: огляд</font> 
</center>

&nbsp;&nbsp;


<center>Кочура Юрій</center>

&nbsp;&nbsp;




*   **Скаляр** &mdash; дійсне число (тензор нульоваго рангу).
*   **Вектор** &mdash;  одновимірний (1D) масив дійсних чисел (тензор першого рангу). Множину векторів довжиною $n$ дійсних чисел позначають $\mathbb{R}^n$.

  *   Вектори можна множити на скаляр.
  *   Вектори можна додавати або віднімати, якщо узгоджені розміри.
  *   Вектори можна перемножувати (скаларний та векторний добуток), якщо узгоджені розміри.

* **Матриця** &mdash;  двовимірний (2D) масив дійсних чисел (тензор другого рангу). Множину матриць розміром $m \times n$ дійсних чисел позначають $\mathbb{R}^{m \times n}$.

  * Матриці можна додавати, віднімати або множити на скаляр.
  * Матрицю можна множити на вектор, якщо узгоджені розміри.



Будемо притримуватись загальноприйнятих позначень: $a$ &mdash; скаляр, $\pmb{a}$ &mdash; вектор (вектор-стовпець),
$\pmb{A}$ &mdash; матриця

# Скаляри 

In [1]:
import numpy as np

In [2]:
x = 3.0
y = 2.0

print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)
print('x ** y = ', np.power(x,y))

x + y =  5.0
x * y =  6.0
x / y =  1.5
x ** y =  9.0


# Вектори

Приклад вектора ``[1.0, 3.0, 4.0, 2.0]``. Ми використовуємо 1D NDArrays.

In [3]:
x = np.arange(12)
print('x = ', x) 

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [4]:
x[3]

3

Форма та тип

In [5]:
x.shape

(12,)

In [6]:
type(x)

numpy.ndarray

# Вектор-стовпець 

In [7]:
x = np.arange(12).reshape(12, 1)
print('x = ', x) 

x =  [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


Форма

In [8]:
x.shape

(12, 1)

# Вектор-рядок 

In [9]:
print('x = ', x.T) 

x =  [[ 0  1  2  3  4  5  6  7  8  9 10 11]]


Форма

In [10]:
x.T.shape

(1, 12)

# Довжина, розмір та форма 

Довжину вектора прийнято називати його *виміром, розміром (dimension)*. Як і у випадку зі звичайним масивом Python, ми можемо отримати доступ до довжини NDArray, викликавши вбудовану функцію Python ``len()``.

Також ми можемо отримати доступ до довжини вектора через його атрибут `.shape`.
Форма &mdash; це кортеж, який перераховує розмір уздовж кожної зі своїх осей.

In [11]:
x.shape

(12, 1)

Ми також можемо отримати загальну кількість елементів в екземплярі NDArray за допомогою атрибуту `.size`

In [12]:
x.size

12

Функція `.reshape()` змінює форму вектора `x` на форму (3, 4), що є матрицею з 3 рядками та 4 стовпцями.

In [13]:
x = x.reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Ми можемо використовувати -1, щоб заповнити значення за замовчуванням. `x.reshape((3, 4))` еквівалентно `x.reshape((-1, 4))` та `x.reshape((3, -1))`

Слово *розмір* має відношення до кількості осей та кількості елементів. **Щоб уникнути плутанини, коли ми говоримо *2D* масив або *3D* масив, ми будемо мати на увазі масив із 2 або 3 осями відповідно. Але якщо ми говоримо *$n$-вимірний* вектор, ми маємо на увазі вектор довжини $n$.**

In [14]:
a = 2
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
print(a * x)
print(a * x + y)

[2 4 6]
[12 24 36]


# Ініціалізація

Метод [`empty`](https://numpy.org/doc/stable/reference/generated/numpy.empty.html) виділяє частину пам’яті. Повертає масив заданої форми та типу без ініціалізації записів.

In [15]:
np.empty((3, 4))

array([[0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323, 3.5e-323],
       [4.0e-323, 4.4e-323, 4.9e-323, 5.4e-323]])

Інколи виникає потреба ініціалізувати кожен елемент тензора нулями. Щоб створити такий тензор форми (2, 3, 4)

In [16]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Ініціалізувати кожен елемент тензора одиницями можна за допомогою методу `ones`

In [17]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Ми також можемо вказати значення кожного елемента в NDArray, який потрібно створити за допомогою списку Python.

In [18]:
 np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

У деяких випадках виникає необхідність ініціалізації кожного елемент тензора випадковим чином. Це особливо часто необхідно, коли ми ініціалізуємо ваги нейронної мережі. У прикладі поданому нижче ми ініціалізуємо тензор форми (3,4). Кожен з його елементів випадково обирається з нормального розподілу з нульовим середнім та дисперсією 1.

In [19]:
mu, sigma = 0, 1
np.random.normal(mu, sigma, size=(3, 4))

array([[ 0.41307296,  0.69003664,  1.99739419,  0.53177931],
       [ 1.30273294,  0.46060757, -0.54233716,  1.39599426],
       [ 0.25679329, -1.02293142, -1.32493548,  1.47126274]])

Багато операцій можна виконувати поелементно. Наприклад, піднесення до степеня

In [20]:
y

array([10, 20, 30])

In [21]:
np.exp(y)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13])

Ми також можемо об’єднати кілька NDArrays. Для цього нам потрібно вказати за яким виміром будемо об’єднати. У наведеному нижче прикладі об’єднано дві матриці вздовж виміру 0 (уздовж рядків) і виміру 1 (вздовж стовпців) відповідно.

In [22]:
x = np.arange(12).reshape((3,4))
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [23]:
np.concatenate((x, y), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [24]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])

## Матриці
Подібно до того, як вектори узагальнюють скаляри від $0D$ до $1D$, матриці узагальнюють вектори від $1D$ до $2D$.
Mатриці зазвичай позначають великими літерами ($\pmb{A}$, $\pmb{B}$, $\pmb{C}$), представлені в коді як масиви з 2 осями.
Візуально ми можемо представити матрицю у вигляді таблиці,
де кожен елемент $a_{ij}$ належить до $i$-го рядка та $j$-го стовпця.


$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix}$$

In [25]:
A = np.arange(20).reshape((5,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Ми можемо отримати доступ до елементів $a_{ij}$, вказавши рядок $i$ і стовпець $j$. Якщо залишити у цих полях `:` буде обрано всі елементи у відповідному вимірі. 


In [26]:
A[1, :]

array([4, 5, 6, 7])

In [27]:
A[:, 1]

array([ 1,  5,  9, 13, 17])

In [28]:
A[1:, 1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

Ми можемо транспонувати матрицю. Тобто, якщо $B = A^T$, то $b_{ij} = a_{ji}$ для будь-яких $i$ та $j$.


In [29]:
A.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

## Тензори

Подібно до того, як вектори узагальнюють скаляри, а матриці узагальнюють вектори, ми можемо збільшити кількість осей. При роботі з зображеннями осі відповідають висоті, ширині і трьом (RGB) кольоровим каналам.

In [30]:
X = np.arange(24).reshape((2, 3, 4))
print('X.shape =', X.shape)
X

X.shape = (2, 3, 4)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## Базові операції з тензорами

Для заданих двох тензорів $X$ та $Y$ з однаковою формою, $\alpha X + Y$ має таку ж форму.

In [31]:
a = 2
x = np.ones(3)
y = np.zeros(3)
print(x.shape)
print(y.shape)
print((a * x).shape)
print((a * x + y).shape)

(3,)
(3,)
(3,)
(3,)


## Сума та середнє

У математиці ми позначаємо суму символом $\sum$.
Для знаходження суми елементів вектора  $\mathbf{u}$ довжиною $n$,
маємо обчислити $\sum_{i=1}^n u_i$. У коді ми просто викликаємо ``np.sum()``.

In [32]:
print(x)
print(np.sum(x))

[1. 1. 1.]
3.0


Аналогічно можна виразити суми за елементами тензорів довільної форми. Наприклад, суму елементів матриці $\pmb{A}$ можна записати $\sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$.

In [33]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [34]:
np.sum(A,0)

array([40, 45, 50, 55])

In [35]:
np.sum(A,1)

array([ 6, 22, 38, 54, 70])

 
Для знаходження середнього значення потрібно суму поділити на загальну кількість елементів тензора. У коді ми просто викликаємо``np.mean()``.

$$\mathrm{Середнє}(\mathbf{u}) = \frac{1}{n} \sum_{i=1}^{n} u_i \text{ та }
\mathrm{Середнє}(A) = \frac{1}{n \cdot m} \sum_{i=1}^{m} \sum_{j=1}^{n} a_{ij}$$

In [36]:
np.mean(x)

1.0

In [37]:
print(np.mean(A))
print(np.sum(A) / A.size)

9.5
9.5


## Скалярний добуток

Для заданих двох векторів $\mathbf{u}$ та $\mathbf{v}$, скалярний добуток $\mathbf{u}^T \mathbf{v}$ &mdash; сума добутків відповідних елементів: $\mathbf{u}^T \mathbf{v} = \sum_{i=1}^{n} u_i \cdot v_i$.

In [38]:
x = np.arange(4) + 1.0
y = np.ones(4)
print(x, y, np.dot(x, y))

[1. 2. 3. 4.] [1. 1. 1. 1.] 10.0


Зверніть увагу, що ми можемо еквівалентно виразити скалярний добуток двох векторів ``np.dot(u, v)``, виконавши поелементне множення, а потім суму:

In [39]:
np.sum(x * y)

10.0

## Норма

Норми вимірюють, наскільки «великим» є вектор. Вони також можуть бути визначені для матриць. Норма  $\ell_p$ для вектора $\mathbf{x}$:
$$\ell_p = ||\mathbf{x}||_p = \Biggl( \sum_{i=1}^n |x_i|^p \Biggr)^{\frac{1}{p}}$$

- Норма  $\ell_1$ також відома як відстань міських кварталів: $||\mathbf{x}||_1 = \sum_{i=1}^n |x_i|$

- Норма  $\ell_2$ також відома як Евклідова відстань: $||\mathbf{x}||_2 = \sqrt{\sum_{i=1}^n |x_i|^2}$

- Норма  $\ell_\infty$ є максимумом (супремумом): $||\mathbf{x}||_\infty = \max_i |x_i|$

Для знаходження $\ell_2$ норми, ми викликаємо ``np.linalg.norm()``.

In [40]:
print(x)
np.linalg.norm(x, 2)

[1. 2. 3. 4.]


5.477225575051661

Для знаходження $\ell_1$ норми, ми просто знаходимо абсолютні значення та обчислюємо їх суму:

In [41]:
np.sum(np.abs(x))

10.0

Або викликавши 

In [42]:
np.linalg.norm(x, 1)

10.0

## Добуток матриця-вектор

$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1m} \\
 a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nm} \\
\end{pmatrix},\quad\mathbf{x}=\begin{pmatrix}
 x_{1}  \\
 x_{2} \\
\vdots\\
 x_{m}\\
\end{pmatrix} $$

$$A\mathbf{x}=
\begin{pmatrix}
\cdots & \mathbf{a}^T_{1} &...  \\
\cdots & \mathbf{a}^T_{2} & \cdots \\
 & \vdots &  \\
 \cdots &\mathbf{a}^T_n & \cdots \\
\end{pmatrix}
\begin{pmatrix}
 x_{1}  \\
 x_{2} \\
\vdots\\
 x_{m}\\
\end{pmatrix}
= \begin{pmatrix}
 \mathbf{a}^T_{1} \mathbf{x}  \\
 \mathbf{a}^T_{2} \mathbf{x} \\
\vdots\\
 \mathbf{a}^T_{n} \mathbf{x}\\
\end{pmatrix}
$$

Отже, ми можемо розглядати множення на матрицю $A\in \mathbb{R}^{m \times n}$ як перетворення, яке проектує вектори з $\mathbb{R}^{m}$ в $\mathbb{R}^{n}$.


Ми також можемо використовувати матрично-векторні добутки для опису обчислень кожного шару нейронної мережі.


Для знаходження матрично-векторних добутків, ми використовуємо функцію ``np.dot()`` як і для скалярних добутків.

In [43]:
A = A.reshape((5,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [44]:
x

array([1., 2., 3., 4.])

In [45]:
np.dot(A, x)

array([ 20.,  60., 100., 140., 180.])

## Добуток матриця-матриця

Якщо ви зрозуміли, як працює множення матриці на вектор, то множення матриці на матрицю не викличе складнощів.

Нехай маємо матриці, $A \in \mathbb{R}^{n \times k}$ та $B \in \mathbb{R}^{k \times m}$:

$$A=\begin{pmatrix}
 a_{11} & a_{12} & \cdots & a_{1k} \\
 a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
 a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{pmatrix},\quad
B=\begin{pmatrix}
 b_{11} & b_{12} & \cdots & b_{1m} \\
 b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
 b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{pmatrix}$$

$$AB = \begin{pmatrix}
\cdots & \mathbf{a}^T_{1} &...  \\
\cdots & \mathbf{a}^T_{2} & \cdots \\
 & \vdots &  \\
 \cdots &\mathbf{a}^T_n & \cdots \\
\end{pmatrix}
\begin{pmatrix}
\vdots & \vdots &  & \vdots \\
 \mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{m} \\
 \vdots & \vdots &  &\vdots\\
\end{pmatrix}
= \begin{pmatrix}
\mathbf{a}^T_{1} \mathbf{b}_1 & \mathbf{a}^T_{1}\mathbf{b}_2& \cdots & \mathbf{a}^T_{1} \mathbf{b}_m \\
 \mathbf{a}^T_{2}\mathbf{b}_1 & \mathbf{a}^T_{2} \mathbf{b}_2 & \cdots & \mathbf{a}^T_{2} \mathbf{b}_m \\
 \vdots & \vdots & \ddots &\vdots\\
\mathbf{a}^T_{n} \mathbf{b}_1 & \mathbf{a}^T_{n}\mathbf{b}_2& \cdots& \mathbf{a}^T_{n} \mathbf{b}_m
\end{pmatrix}
$$

Ми можемо розглядати добуток двох матриць $AB$ просто як виконання $m$ добутків матриця-вектор та об’єднання результатів.

In [46]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
B = np.ones(shape=(4, 3))
np.dot(A, B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

<a href="https://colab.research.google.com/github/YKochura/ai-lab/blob/main/math/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>